name: "100 Algorithm Linter"

on: [push, pull_request]

jobs:

  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run linter
        run: |
              cd "100-js-algo"
              npm install
              npm run lint
        shell: bash
