name: Run Node Unit Test

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubunut-latest
    defaults:
      run:
        shell: bash
        working-directory: pwd
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12