name: "100 Algorithm Challenge"

on:
  push:
    branches: 
      - master
      - 100-algo-challenge
    paths:
      - "**.js"

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Test in 100-js-algo
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install node modules
      run: npm install
    - name: Run test
      run: npm run test
